[package]
name = "love-waifu"
version = "0.1.0"
edition = "2021"

[dependencies]
rig-core = "0.0.6"
tokio = { version = "1.0", features = ["full"] }
dotenv = "0.15.0"
anyhow = "1.0"
twitter-v2 = "0.1.8"